"""add_fraud_cases_and_case_events

Revision ID: ad9bb1c5a7e3
Revises: 20fde37cd97b
Create Date: 2026-08-28 17:40:12.452966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9bb1c5a7e3'
down_revision: Union[str, Sequence[str], None] = '20fde37cd97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_fraud_cases_case_id'), 'fraud_cases', ['case_id'], unique=False)
    op.create_table('case_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_case_events_event_id'), 'case_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_events_event_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_fraud_cases_case_id'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    # ### end Alembic commands ###
